### ISSUE TITLE
R: getDailyWxObservations not returning 'date' vector

### ISSUE THREAD

**Issue by aaronweed** [IMDProjects/IM_Climate#12]
In R, when I run : 

df<-getDailyWxObservations(list('pcpn', 'avgt', 'obst', 'mint', 'maxt'), 25047, "2016-01-01", "2016-05-01")
str(df)

,for example, I am not getting back the date vector in the dataframe.

**Comment by llnelson** [comment]
@aaronweed Doh - fixed!
