### ISSUE TITLE
Confirm and Update StnMeta validDateRange format

### ISSUE THREAD

**Issue by llnelson** [IMDProjects/IM_Climate#17]

**Comment by llnelson** [comment]
If consistent, implement MinRange, MaxRange output

**Comment by BrentFrakes** [comment]
I have confirmed that ACIS is consistently returning the correct date ranges per parameter:

        #Confirm that the start/end dates returned for a station are always the same
        wxStations = sf.findStation(parkCodes = 'ROMO', climateParameters = 'mint, maxt, pcpn, snwd')
        self.assertEqual(wxStations[4072].validDateRange['mint']['begin'], datetime.date(1939, 10, 1))
        self.assertEqual(wxStations[4072].validDateRange['pcpn']['begin'], datetime.date(1907, 10, 1))
        self.assertEqual(wxStations[4072].validDateRange['snwd']['begin'], datetime.date(1908, 10, 19))

        wxStations = sf.findStation(parkCodes = 'ROMO', climateParameters = 'pcpn, snwd ,mint, maxt')
        self.assertEqual(wxStations[4072].validDateRange['mint']['begin'], datetime.date(1939, 10, 1))
        self.assertEqual(wxStations[4072].validDateRange['pcpn']['begin'], datetime.date(1907, 10, 1))
        self.assertEqual(wxStations[4072].validDateRange['snwd']['begin'], datetime.date(1908, 10, 19))

        wxStations = sf.findStation(parkCodes = 'ROMO', climateParameters = 'snwd ,mint, maxt, pcpn')
        self.assertEqual(wxStations[4072].validDateRange['mint']['begin'], datetime.date(1939, 10, 1))
        self.assertEqual(wxStations[4072].validDateRange['pcpn']['begin'], datetime.date(1907, 10, 1))
        self.assertEqual(wxStations[4072].validDateRange['snwd']['begin'], datetime.date(1908, 10, 19))

**Comment by BrentFrakes** [comment]
I've checked in my code

**Comment by llnelson** [comment]
Committed initial implementation of valid date range output. However, need to resolve question in package doc: https://docs.google.com/document/d/1B0rf0VTEXQNWGW9fqg2LRr6cHR20VQhFRy7PU_BfOeA/edit?disco=lkptja2987wd

**Comment by llnelson** [comment]
Verified 20160822
