### ISSUE TITLE
R: DataRequestor - Quotes around text

### ISSUE THREAD

**Issue by BrentFrakes** [IMDProjects/IM_Climate#29]
The one difference remaining is the following:
R: '"uid","name","longitude","latitude","sid1","sid1_type","sid2","sid2_type","sid3","sid3_type","state","elev",

PYTHON: 'uid,name,longitude,latitude,sid1,sid1_type,sid2,sid2_type,sid3,sid3_type,state,elev,

Note that you do not include quotes with the StationFinder function

**Comment by llnelson** [comment]
Decision: will enclose character strings in quotes (").
