### ISSUE TITLE
Py/R: getWxObs - add default of all climate params

### ISSUE THREAD

**Issue by llnelson** [IMDProjects/IM_Climate#33]
Assume ACIS returns blank values for date range if no data exist.

**Comment by llnelson** [comment]
Added for R.  20160901

**Comment by llnelson** [comment]
@BrentFrakes Note: do a pull to get the updated ACISLookups.json

**Comment by llnelson** [comment]
And, I'm not including the degree days params in the default list.  Do you concur? @BrentFrakes

**Comment by BrentFrakes** [comment]
Yes I concur:  we do not presently support cdd,hdd or gdd

I upated my code, added a new test, and pushed changes

**Comment by llnelson** [comment]
Closed 20160906
