### ISSUE TITLE
ACIS Gridded Data seems to be coming back in reverse order (ie.e, south at top)

### ISSUE THREAD

**Issue by BrentFrakes** [IMDProjects/IM_Climate#34]
Lisa, please confirm if you are seeing this

**Comment by llnelson** [comment]
Looks like ACIS supports only one output projection: Lambert Conformal Conic.  See:  [http://www.rcc-acis.org/docs_webservices.html#title24](http://www.rcc-acis.org/docs_webservices.html#title24)  

Let's look into this more on Monday.

**Comment by llnelson** [comment]
Is this still occurring? I had to flip columns when generating ASCII output. Do you do that in Python?

**Comment by BrentFrakes** [comment]
Yes - I am flipping

**Comment by llnelson** [comment]
Since we both flip, closing this issue. @BrentFrakes
