### ISSUE TITLE
R: findStation: is "distance" argument really optional?

### ISSUE THREAD

**Issue by aaronweed** [IMDProjects/IM_Climate#4]
I've tried the following and am not getting a df back:

findStation("MABI",  climateParams= "avgt") OR
findStation("MABI", distance= NULL, climateParams= "avgt")

We should probably include a better description of what "NULL" distance is doing and provide examples in the Arguments section of the function documentation.

**Comment by llnelson** [comment]
Need to document what the default is

**Comment by BrentFrakes** [comment]
I'm getting 19 stations back - I've added it as Test Case #7

On Thu, Jul 7, 2016 at 9:39 AM, llnelson <notifications@github.com> wrote:

> Need to document what the default is
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/IMDProjects/IM_Climate/issues/4#issuecomment-231117523>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFq2VyeJOY1HrfJ9tiKOWUqeEm5zQWPVks5qTR2agaJpZM4JHKTw>
> .
>



-- 
Brent Frakes
Inventory and Monitoring Division
National Park Service
1201 Oakridge Drive - #150
Fort Collins, CO 80525
Phone: 970-267-2156

**Comment by llnelson** [comment]
I get stations back from most parks when I leave the distance parameter out. E.g. 
```
findStation(parkCodes = "FRSP", climateParams= "pcpn") 
findStation(parkCodes = "FOLA", climateParams= "avgt")
```

For MABI, specifically, I get no stations with a NULL or missing distance.  Using distance=1, I get 1 station: 
`findStation(parkCodes = "MABI", 1, climateParams= "avgt")`

Brent, I cannot replicate 19 stations returned for the 
`wxStations = sf.findStation(unitCode = 'MABI', parameter = 'avgt')`
request.

**Comment by BrentFrakes** [comment]
This is what I am posting:
{'bbox': '-72.2236975283, 43.296986326,-72.8373492201,43.9703113389',
 'elems': 'avgt',
 'meta': ['uid', 'name', 'state', 'll', 'elev', 'valid_daterange', 'sids']}

**Comment by BrentFrakes** [comment]
I have now set the default buffer to 0
