### ISSUE TITLE
raise Exception with note if ACIS response is 'error'

### ISSUE THREAD

**Issue by BrentFrakes** [IMDProjects/IM_Climate#43]
raise Exception('ACIS Service Error: ' + Error)

**Comment by llnelson** [comment]
In R package, error from ACIS is passed through to output. For example, a getWxObs request with erroneous parameters returns "no data available".  From the R perspective, this can be closed. @BrentFrakes

**Comment by llnelson** [comment]
Verify that "no data available" is returned in Python @BrentFrakes. If so, you can close this issue.

**Comment by BrentFrakes** [comment]
changed to return "no data available"
