### ISSUE TITLE
R:findStation: filePathAndName prevents object from saving in local environment

### ISSUE THREAD

**Issue by aaronweed** [IMDProjects/IM_Climate#5]
I think it was meant to be this way but it would be nice to save in local environment too so you can check that the output is what you want. 

When you enter something like:
stat<- findStation("MABI", distance= 30, climateParams= "pcpn",filePathAndName= "mabi.csv")

the function only returns the csv file and not the stat object. If you remove the "else" in the code snippet below or add in "return(dataResponse)" as you did in getDailyWxObservations it should work..

if (!is.null(filePathAndName)) {
        write.table(stationList, file = filePathAndName, sep = ",", 
            row.names = FALSE, qmethod = "double")
 else {
        return(stationList)

**Comment by llnelson** [comment]
Make consistent with wx function behavior

**Comment by llnelson** [comment]
Fixed.
