### ISSUE TITLE
Feature Request: Save climate grids and projection information to memory instead of disk

### ISSUE THREAD

**Issue by johnpauls** [IMDProjects/IM_Climate#52]
It would be nice to have the option in `getDailyGrids` to just save the gridded climate info / projections as a list in memory (for R, not sure what Python equivalent is) rather that as files on disk. I would use this for visualization in particular.

**Comment by BrentFrakes** [comment]
As for python, in memory the grids reside in a "stack" (aka dictionary) that is indexed by parameter and date.

**Comment by llnelson** [comment]
JP, do you want a raster stack or some other format? @johnpauls

**Comment by johnpauls** [comment]
Good question @llnelson   - I will play with this some and get back to you soon.

**Comment by llnelson** [comment]
Hi again - any further thoughts on this? @johnpauls

**Comment by johnpauls** [comment]
Sorry, got busy on other things and did not get back to this. I think raster stack is the way to go. Basically I am hoping to dynamically add these rasters to a leaflet map, either on its own or as part of a shiny app. TO do this I would be using [`addRasterImage`](http://rstudio.github.io/leaflet/raster.html) from the leaflet package. This in turn requires a raster layer form the `raster` package, so a raster stack seems like the way to go. Thanks.

**Comment by llnelson** [comment]
Example: Alamosa NWR in Colorado

![image](https://cloud.githubusercontent.com/assets/6653439/21030689/2bd39252-bd5d-11e6-9517-0777b4a862e5.png)

**Comment by llnelson** [comment]
Please test (see examples in demo.R script).  You will need to use the dev branch, not the master branch.  @johnpauls
