### ISSUE TITLE
Change order of results output

### ISSUE THREAD

**Issue by BrentFrakes** [IMDProjects/IM_Climate#59]
Iteration in the following order:
Parameter
   aggregate

**Comment by llnelson** [comment]
Climate parameter order (station): 'pcpn', 'mint', 'maxt', 'avgt', 'obst', 'snow', 'snwd'

Climate parameter order (grids): 'pcpn', 'mint', 'maxt', 'avgt'

Reduce code order:  'min', 'max', 'sum', 'mean'

@BrentFrakes

**Comment by BrentFrakes** [comment]
done
