### ISSUE TITLE
TODO: R: Update "Value" documentation in findStation and getDailyWxObservations function documentation

### ISSUE THREAD

**Issue by aaronweed** [IMDProjects/IM_Climate#6]

**Comment by llnelson** [comment]
Add detail on what the df contains

**Comment by llnelson** [comment]
@aaronweed I've forgotten the details on this issue - do I just need to add an output example to the Value section of the RDoc?

**Comment by llnelson** [comment]
[www.google.com](www.google.com)

**Comment by aaronweed** [comment]
You wrote" do I just need to add an output example to the Value section of the RDoc?"

I was suggesting documentation of each element of the dataframe with a small description, so that users know what sid1 is, units of all data observations, etc. I will work on this

**Comment by llnelson** [comment]
add ink to doc
