### ISSUE TITLE
Resolve method name discprepency for get monthly wx observations (per year)

### ISSUE THREAD

**Issue by BrentFrakes** [IMDProjects/IM_Climate#64]
Our method names are not the same

**Comment by llnelson** [comment]
And, what are your test case params for test #3: https://github.com/IMDProjects/IM_Climate/tree/dev/TestExamples/StationDataRequestor/getMonthlyWxSummaryByYear  
Not seeing test 3 in Tests.txt file; please add. @BrentFrakes

**Comment by llnelson** [comment]
Method name in R package is now getWxObservations().  20170206.

**Comment by BrentFrakes** [comment]
What is the name of the argument indicating that it is daily, monthly or annual? @llnelson

**Comment by llnelson** [comment]
Correct @BrentFrakes

**Comment by bfrakes** [comment]
I've added a getWxObservations method
