### ISSUE TITLE
Consolidate grid requests into one method for daily, monthly and yearly

### ISSUE THREAD

**Issue by BrentFrakes** [IMDProjects/IM_Climate#67]
Current no need to break those out into three different methods

**Comment by llnelson** [comment]
Confirm Py does not use the interval param

**Comment by llnelson** [comment]
Done in R, I think (minus the yearly param).  Need to discuss. @BrentFrakes

**Comment by llnelson** [comment]
Add yearly to R package.

**Comment by llnelson** [comment]
DOH - I did add yearly to the R package.  Adding test outputs now. @BrentFrakes

**Comment by llnelson** [comment]
Completed 20170208  Commit: 7266808
