### ISSUE TITLE
Verify extent and CRS for raster outputs

### ISSUE THREAD

**Issue by llnelson** [IMDProjects/IM_Climate#69]
R: try setting extent (from LL values) or ?; see https://www.nceas.ucsb.edu/~frazier/RSpatialGuides/OverviewCoordinateReferenceSystems.pdf and http://geostat-course.org/system/files/geostat13_in%2526outAM.pdf

Py: confirm rasters are returned in NAD83 geographic

**Comment by llnelson** [comment]
R: Added extent to raster stack; confirm this occurs for Python

**Comment by llnelson** [comment]
Working in R; confirm spatial reference (CRS) and extent displays correctly when plotting in Python. @BrentFrakes

**Comment by BrentFrakes** [comment]
I am not plotting in python so this is not relevant at present @llnelson
