### ISSUE TITLE
R: getDailyWxObservations v0.1 output latitude and longitude vectors

### ISSUE THREAD

**Issue by aaronweed** [IMDProjects/IM_Climate#7]
If possible, please force the latitude and longitude output vectors to be numeric rather than a factor.

**Comment by llnelson** [comment]
@aaronweed Am I missing something here? The typeof calls from this code returns 'double': 

```
xx <- findStation(parkCodes = "FRSP", climateParams= "pcpn")
typeof(xx$longitude)
typeof(xx$latitude)

```

**Comment by aaronweed** [comment]
Wrong function. I amusing getDailyWxObservations not findStation. findStation works great.

**Comment by llnelson** [comment]
Doh!!  Fixed
