### ISSUE TITLE
STICKY: IM_Climate toolkit spreadsheet and Package Doc

### ISSUE THREAD

**Issue by llnelson** [IMDProjects/IM_Climate#8]
Package doc: https://docs.google.com/document/d/1B0rf0VTEXQNWGW9fqg2LRr6cHR20VQhFRy7PU_BfOeA

Spreadsheet: https://docs.google.com/spreadsheets/d/1gqPr6kbPQ0PP2jw8rSs6BakySaTWbRAXj1aDSYumQEM

**Comment by BrentFrakes** [comment]
no need for this
